# default video options
vo=gpu

# png screenshots 
screenshot-format=png
screenshot-png-compression=8

# stop screensaver breaks xautolock
no-stop-screensaver

# screenshot template
screenshot-template="%F-%P"

# subtitles
sub-font="Noto Sans"

# loop webms
[extension.webm]
loop-file=yes

# progress bar and no attached picture
[audio]
term-osd-bar=yes
no-audio-display

# use profile for audio files
[extension.flac]
profile=audio
[extension.mp3]
profile=audio
[extension.opus]
profile=audio

# high fps
[highfps]
profile-desc=cond:get('container-fps', 0) >= 45
deband=no

# videos smaller than HD+
[high]
profile-desc=cond:get('width', math.huge) < 1600 and get('container-fps', 0) < 45
profile=gpu-hq
video-sync=display-resample
interpolation
tscale=oversample

# videos smaller than QHD
[medium]
profile-desc=cond:get('width', math.huge) < 2560 and get('container-fps', 0) < 45
video-sync=display-resample
interpolation
tscale=oversample

# videos QHD or larger
[low]
profile-desc=cond:get('width', math.huge) >= 2560 and get('container-fps', 0) < 45
deband=no
