# images
mime ^image, has imv,      X, flag f = imv -- "$@"
# pdf
ext pdf, has zathura,      X, flag f = zathura "$@"
# audio and video
mime ^audio|ogg$, terminal, has mpv  = mpv -- "$@"
mime ^video, has mpv,      X, flag f = mpv -- "$@"
# documents
ext pptx?|od[dfgpst]|docx?|sxc|xlsx?|xlt|xlw|gnm|gnumeric, has libreoffice, X, flag f = libreoffice "$@"
# text
mime ^text,  label editor = $EDITOR -- "$@"
mime ^text,  label pager  = "$PAGER" -- "$@"
!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = $EDITOR -- "$@"
!mime ^text, label pager,  ext xml|json|csv|tex|py|pl|rb|js|sh|php = "$PAGER" -- "$@"
