#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

# top padding for polybar
bspc config top_padding         25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# no gaps for single window
bspc config single_monocle       true

# focus following mouse
bspc config focus_follows_pointer true

# ptr cursor
xsetroot -cursor_name left_ptr &

# set non reparenting env variable for java
export _JAVA_AWT_WM_NONREPARENTING=1

# launch polybar
$HOME/.config/polybar/launch.sh
